version: '3.1'

services:
  web:
    image: upraised/jobportal:1.0
    ports:
      - "9090:8080"
    depends_on:
      - postgres
  postgres:
    image: postgres:10.12
    ports:
      - "9999:5432"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=job_portal
    volumes:
      - ./database/data/postgres:/var/lib/postgresql/data
