version: '3.1'

services:
  postgres:
    image: mypostgres:10.12
    container_name: my-postgres-container
    ports:
    - "9999:5432"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=job_portal
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
