version: '3.1'

services:
  postgres:
    image: postgres:10.12
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=job_portal
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
