package com.upraised.database.datatypes;

public enum Category {
  CLEANTECH,
  E_COMMERCE,
  EDTECH,
  ENTERPRISETECH,
  FINTECH,
  FMCG,
  HEALTHTECH,
  MARKETPLACES,
  MEDIA_AND_ENTERTAINMENT,
  TRANSPORTTECH,
  TRAVELTECH
}
